name: "GitHub Action Xcode Cloud"
description: "Trigger Xcode Cloud Workflows via GitHub Actions."
author: "inventas"

branding:
  icon: "cpu"
  color: "blue"

inputs:
  keyId:
    description: "Key ID from App Store Connect."
    required: true
  key:
    description: "P8 private key from App Store Connect."
    required: true
  issuerId:
    description: "Issuer ID from App Store Connect."
    required: true
  xcodeCloudWorkflowId:
    description: "Workflow ID in Xcode Cloud obtained by inspecting the URL https://appstoreconnect.apple.com/teams/{team-id}/apps/{app-id}/ci/workflows/{workflow-id}."
    required: true
  gitBranchName:
    description: "Name of the Git branch to trigger the workflow on."
    required: true

outputs:
  buildNumber:
    description: "The build number"
  buildId:
    description: "The build ID"
  gitReferenceId:
    description: "The git reference ID"

runs:
  using: "node24"
  main: "dist/index.js"
